### ISSUE TITLE
Many insertion commands are missing the 'delete-selection property

### ISSUE THREAD

**Issue by cpitclaudel** [abo-abo/lispy#119]
When `delete-selection-mode` is active, selecting text and pressing space (for example) removes the selected text before inserting the space. `lispy-mode` breaks this behaviour by rebinding space.

From the `delete-selection-mode` docs:

```
;; Commands which will delete the selection need a 'delete-selection
;; property on their symbols; commands which insert text but don't
;; have this property won't delete the selection.  It can be one of
;; the values:
;;  `yank'
;;      For commands which do a yank; ensures the region about to be
;;      deleted isn't yanked.
;;  `supersede'
;;      Delete the active region and ignore the current command,
;;      i.e. the command will just delete the region.
;;  t
;;      The normal case: delete the active region prior to executing
;;      the command which will insert replacement text.
;;  <function>
;;      For commands which need to dynamically determine this behavior.
;;      The function should return one of the above values or nil.
```

Cheers,
Clément

**Comment by abo-abo** [comment]
This behavior is by design: `delete-selection-mode` isn't compatible `lispy-mode`.  Making it compatible would cripple the functionality of lispy, since many commands have special behaviors when the region is active, instead of doing the very simple thing of deleting the region and self-inserting.

For example, <kbd>M-m</kbd> marks symbol-at-point. So:

- <kbd>M-m e</kbd> will evaluate the current symbol
- <kbd>M-m je</kbd> will evaluate the next symbol
- <kbd>M-m njP</kbd> will replace the next symbol with the current symbol
- <kbd>m&gt;</kbd> will mark the current and the next list etc

Having the commands work when the region is active allows to operate not only on single lists, but also on sequences of lists and symbols.

**Comment by cpitclaudel** [comment]
Ok; thanks for the explanation. I was thinking mostly of the case of `space`; if the command is indeed going to end up just inserting a space at the end of the region, then maybe it would be nice to have the replacement behaviour in that situation. But the consistency aspect might trump that.

**Comment by abo-abo** [comment]
The current behavior of <kbd>SPC</kbd> makes sense to me. Imagine a situation like this:

    (list ~(foo)| (bar))

Here, as in all `lispy` documentation and tests `~` denotes the mark position and `|` denotes the point position.  If you want to insert an element after `(foo)` you press <kbd>SPC</kbd> to deactivate the region and insert once space.  Additionally, <kbd>RET</kbd> works in the same way: deactivate the region and call `newline-and-indent`.

You can redefine those commands to replace the region if you want, but I think that would require more mental effort having to remember to deactivate the region before inserting space or newline.

The way it works now, it almost doesn't matter if the region is active or not: commands like <kbd>j</kbd> or <kbd>s</kbd> will work similarly.  This allows for more efficiency by not having to toggle in and out of region all the time, and instead stay in whatever state that requires less key strokes.
