### ISSUE TITLE
lispy-slurp refuses to slurp when a sexp is marked and next to #_

### ISSUE THREAD

**Issue by Peeja** [abo-abo/lispy#154]
Kind of a weird one to describe. Below, `|` is the point and `⦊foo⦉` is the region.

```
(foo) #_|⦊(bar)⦉ (baz)
```

I would expect pressing <kbd>></kbd> (`lispy-slurp`) here to expand the region to include the `#_`, but it does nothing. Curiously, it also does nothing when the point is on the other side. It also does nothing if the `#_` is on the other side of the marked form. Thus, `lispy-slurp` does nothing in these cases either:

```
(foo) #_⦊(bar)⦉| (baz)
(foo) |⦊(bar)⦉#_ (baz)
(foo) ⦊(bar)⦉|#_ (baz)
```

(By the way, I hope you don't mind all these bug reports. I file them to be helpful, and I hope they don't come across as demanding. I'm *hugely* grateful for your work on Lispy.)

**Comment by abo-abo** [comment]
> By the way, I hope you don't mind all these bug reports.

I'm hugely grateful for your bug reports. If a feature is working in a wrong way and is reasonable to fix, it's 100x times better that I'm notified about it.  I have many blind spots, for instance I'm not working with Clojure regularly. So I appreciate being updated on things that don't work correctly.

> Kind of a weird one to describe.

See the two tests that I added in this commit:

```elisp
(should (string= (lispy-with "(foo) #_~(bar)| (baz)" ">")
                 "(foo) #_~(bar) (baz)|"))
(should (string= (lispy-with "(foo) #_|(bar)~ (baz)" ">")
                 "(foo) |#_(bar)~ (baz)"))
```

This is a convenient API for both testing and documenting the code. It can also be convenient for reporting bugs.  Note my notation of point and mark: point is `|` and mark is `~`. If the mark is present, the region is active, otherwise it's not.

There's also an option to view these tests conveniently (in case the text spans many lines) by pressing <kbd>xv</kbd>.

**Comment by Peeja** [comment]
Cheers!
