### ISSUE TITLE
Prevent lispy-delete from unbalancing parens when operating on a region

### ISSUE THREAD

**Issue by noctuid** [abo-abo/lispy#206]
After seeing luxbock/evil-cleverparens#34, I'm interested in writing something similar to `evil-lispy`. For this purpose, having an existing function like `(safe-delete-region beg end)` would make things a lot easier. I also think that having something like this could be beneficial for regular lispy users which is why I'm making this issue.

I notice that currently when the region is active, `lispy-delete` just calls `delete-region` which can result in unbalanced parenthesis. I think it would be nice if instead lispy-delete ensured that the result was still properly balanced. I realize that deleting a region may not be as useful in general as deleting sexps, but I still think this could be helpful.

There are different ways to handle this, but I think that these are good, simple rules:
1. Any sexp with both its open and closing parens in the region is completely deleted.
2. Otherwise, the parens are left intact, but all other characters in the region are deleted.

Some examples where `| |` represents the active region:
```
|(a |b)
;; becomes
(b)
```

```
(list 'a
      |(list 'b))|
;; becomes
(list 'a
      )
```

```
(list 'a|
      (list 'b))|
;; becomes
(list 'a)
```
It would also be nice if there was a way to copy a region without copying unbalanced parenthesis. In this case it might be better to only copy fully enclosed sexps instead of using the above rules. Maybe it would be nice to be able to both kill and yank with either of these two possible rules

Also it could be nice to have `lispy-paste` automatically balance the blocks in whatever is to be pasted.

**Comment by abo-abo** [comment]
> I notice that currently when the region is active, lispy-delete just calls delete-region which can result in unbalanced parenthesis.

I assume that a person uses lispy commands to activate and manipulate the region. They always leave it in a consistent state for `delete-region`. If they ever don't, it's a bug that should be reported and fixed.

On the other hand, using regular motions for region selection means the person probably wants to subvert lispy in order to do something clever. So I make lispy act dumb in that case as not to get in the way (and possibly lead to cleverness escalation). Of course, this is mostly true for <kbd>C-w</kbd>, which is still bound to `kill-region`, <kbd>C-d</kbd> is modeled after it. I don't see a problem with improving <kbd>C-d</kbd> with an active region, as long as it doesn't get too clever.


> 1. Any sexp with both its open and closing parens in the region is completely deleted.

OK.

> 2. Otherwise, the parens are left intact, but all other characters in the region are deleted.

This is new, but sort-of makes sense.

> Some examples where | | represents the active region:

If you indent do contribute, which I really welcome, you need to be familiar with the test suite.  In the test suite, `|` represents the point and `~` represents the mark. This notation offers more information.

    ~(a |b)
    ;; becomes
    (b)

It occurs to me that the point and the mark can be seen as delimiters, just like open and closed paren.  Above they are in an inconsistent state.

> It would also be nice if there was a way to copy a region without copying unbalanced parenthesis

Starts to sound too clever.

> also it could be nice to have lispy-paste automatically balance the blocks in whatever is to be pasted.

This is a bad idea, in my opinion. Having invariants is a good thing. Invariants take away the complexity. Having balanced code in the kill ring is a nice invariant. Attempting to balance unbalanced code will result in a huge amount of bugs and failed expectations. Like when you want to fix something and there are two ways to do it: either way you choose is wrong for someone, because it's not what they expect.

In any case, feel free to PR with `safe-delete-region`. It's useful for corner cases where the invariants are not met. But I think we should try to meet the invariants rather than rely on `safe-delete-region`.

**Comment by noctuid** [comment]
> the person probably wants to subvert lispy in order to do something clever.

That's a good point. I think this would be more useful for people who might want to lazily select parts of a sexps or full lines (and to evil users). I agree that this functionality shouldn't be the default if added.

> Attempting to balance unbalanced code will result in a huge amount of bugs and failed expectations.

All I would suggest is an option to add the missing delimiters at the end instead of trying to do anything smarter. The only time I have unbalanced code in the kill ring is when I've copied part of something outside of emacs and am missing trailing parentheses. In other cases, the user would have to correct whatever they pasted themselves or just disable this option. This is a rare case, and relying on having balanced code in the kill ring generally seems like a better idea. Would you accept having the approach of just adding missing closing delimiters at the end as an option (off by default)?

I will look into the lispy test suite and maybe make a PR. Would you accept a PR that had both `lispy--safe-delete-region` and `lispy--safe-copy-region`? They would basically be the same apart from the action.

Now that I think about it, the 2nd rule I suggested above doesn't really have useful behavior in a lot of situations. Consider the following example:
```
(li~st (li|st 'a))
;; becomes
(li(|st 'a))
```
Cleverparens does things this way but currently acts inconsistently depending on how much of a symbol is selected. I think a simpler method might be to take the largest safe part of a region and act on it instead of worrying about deleting parts of symbols and text in the unsafe part of the region. Basically, if there is a safe sub-region in the active region, the active region is shrunk to that region. If there is not a safe region contained (unbalance in both directions instead of one), the active region expands to make the region safe. If there is no possible safe region (the code is currently unbalanced), the operation aborts.

This would have the same behavior as before here:
```
~(a |b)
;; acts as
(~a |b)
;; becomes
(|b)
```

and here:
```
(list
 ~(list (list 'a)))|
;; acts as 
(list
 ~(list (list 'a))|)
;; becomes
(list
 |)
```

In this situation it would need to expand in both directions:
```
(list~ 'a)
(list| 'b)
;; acts as
~(list 'a)
(list 'b)|
;; becomes nothing
```

Would this behavior be acceptable?

**Comment by abo-abo** [comment]
> Would you accept having the approach of just adding missing closing delimiters at the end as an option (off by default)?

Yes, this sounds fine.

> I will look into the lispy test suite and maybe make a PR. Would you accept a PR that had both lispy--safe-delete-region and lispy--safe-copy-region? They would basically be the same apart from the action.

Yes.

> Would this behavior be acceptable?

Shrinking until the delimiter is matched sounds unambiguous enough. But the expectation might be that the other side should be growing instead. We can try it out, see how it feels.

**Comment by noctuid** [comment]
I'm using `lispy--bounds-list` in and implementation and notice that the point is considered in a list if it is before the opening paren but not if it is after the closing paren.

For example:
```
;; with the point here
(a |(b c) d)
;; these are the returned bounds
(a |(b c)| d)
;; and with the point here
(a (b c)| d)
;; these are the returned bounds
|(a (b c) d)|
```
I just want to confirm whether this is how `lispy--bounds-list` should act.

**Comment by abo-abo** [comment]
Yes, `lispy--bounds-list' should return something that you'd like to eval.

**Comment by noctuid** [comment]
Thanks for merging.
