### ISSUE TITLE
Should lispy--current-function return the same string at either end of sexp?

### ISSUE THREAD

**Issue by sooheon** [abo-abo/lispy#217]
Most lispy functions (move up or down, raise, mark, etc.) do the same logical thing on both sides of the sexp, which makes `d` a no-brainer operation, I don't have to worry which side my cursor is on when I call something. `lispy--current-function` seems to be an exception.

```
(defun foo ()
  [a](interactive)[b])
```

`C-1` or `C-2` at [a] or [b] give different results. Would it be possible to make this symmetrical as well? For the reason why, I think it makes sense that `C-1` should give docs for the same function that it would evaluate with `e`.

**Comment by abo-abo** [comment]
I don't think it should. You should be able to get the doc of the containing list.

From this position, you get the doc of `interactive`, since the opening delimiter is part of its containing list, and the point is considered to belong to `interactive`:

    (defun foo () |(interactive)
    
From this position, you get the doc of `defun`, since the closing delimiter is not part of its containing list, and the point is considered to belong to `defun`:

    (defun foo () (interactive)|
    
The idea is to get the doc for the thing you are currently typing. With the point as above, you've finished typing the `interactive` form and are now typing the `defun` form.

**Comment by sooheon** [comment]
Ah fair enough.
