### ISSUE TITLE
Updating Documentation

### ISSUE THREAD

**Issue by noctuid** [abo-abo/lispy#229]
I can start updating the documentation to include the recently added functionality and changes if you'd like. I want to make sure I'm generating the html correctly. How have you been generating the html from index.org?

Also, I'm not sure exactly where to put the new unbound commands. Did you want to have some of them in the paredit map as well?

**Comment by abo-abo** [comment]
> How have you been generating the html from index.org?

Just plain Org export to HTML: <kbd>C-c C-e ho</kbd>. However, it's broken right now for the current Org, since they changed some stuff.  It should still work with the built-in Org of 24.5.  If you want, replace the `#+BEGIN_HTML` stuff with the new ones to make it run on the newest Org.

> Did you want to have some of them in the paredit map as well?

I'm OK with this, as long as you don't shadow the common bindings in the paredit map.  So don't touch stuff like <kbd>M-m</kbd> - even though I think the default binding for it is useless, some people like it.

**Comment by noctuid** [comment]
I tried generating it with the built-in org for 24.5, but the generated html has no syntax highlighting.

> #+BEGIN_HTML stuff with the new ones

Where would I find them?

**Comment by abo-abo** [comment]
I just updated, the export should now work fine with the new Org.

**Comment by noctuid** [comment]
I tried exporting with the latest org (20160328), and there are quite a few more problems now. Is there a specific version I should be using or anything else that could cause this?

![generated htmll](https://cloud.githubusercontent.com/assets/4250696/14219281/6ed816d2-f827-11e5-8856-d1a770e66d19.png)

**Comment by abo-abo** [comment]
Try using the newly added Makefile.

**Comment by abo-abo** [comment]
Doesn't hurt to have them, but maybe they should be on their separate pages, e.g. `parinfer_index.html`.
