### ISSUE TITLE
slurping with quotes

### ISSUE THREAD

**Issue by mallt** [abo-abo/lispy#305]
To make slurping (and barfing) work with quotes as well, I've added quotes to lispy-left and lispy-right:
`(setq lispy-left "[([{\"]")`
`(setq lispy-right "[])}\"]")`

Although this seems to work without any immediate problems, I was wondering if it would have drawbacks to do so, or if there is another way to get a similar behavior in lispy?

Thanks a lot!

**Comment by abo-abo** [comment]
> Although this seems to work without any immediate problems, I was wondering if it would have drawbacks to do so, or if there is another way to get a similar behavior in lispy?

I'm surprised it works at all. There's no default way to slurp with quotes, since it's not a frequent operation for me.

But here's a trick that also works:

1. Mark the string with a region (<kbd>M-m</kbd> or something else).
2. Use <kbd>'</kbd> to unquote the string.
3. Use `>` to slurp.
4. Use `"` to re-quote.

**Comment by mallt** [comment]
Ok I see, slurping with regions, that's really nice!
Thanks a lot!
