### ISSUE TITLE
lispy--find-safe-regions in code following comment

### ISSUE THREAD

**Issue by braham-snyder** [abo-abo/lispy#364]
Thanks a ton for `lispy`!

With `lispy` and `lispy-safe-delete`, and with `mark` as `~` and `point` as `|`
(or vice versa):

```
(message
 ;; f|oo
 bar)~
```

`lispy-delete` leaves:

```
(message
 ;; f)
```

I'm guessing `lispy-safe-actions-ignore-comments` shouldn't apply here since
`region` is not enclosed by one comment, but FWIW I see the same behavior above
regardless of its value.

same issue, surely: https://github.com/noctuid/lispyville/issues/8

**Comment by abo-abo** [comment]
The way I use it, once you have your region in an inconsistent state, all bets are off. Same as with unbalanced parens.

@noctuid authored `lispy-safe-delete`. Can you comment?

**Comment by noctuid** [comment]
When `lispy-safe-actions-ignore-comments` is non-nil, it applies regardless of whether the region is enclosed by one comment. It will just ignore delimiters in comments and consider them deletable. Since there are no delimiters in the original comment, its value doesn't matter here.

When I looked into adding this functionality to lispyville, the resulting code ended up being too complicated, and it wasn't an issue I ever encountered myself. That said, I I can probably make a simpler pull request to lispy that will fix this. I'll look into it.

**Comment by noctuid** [comment]
@braham-snyder I opened a pull request (also works for safe pasting). The setting is disabled by default. Let me know if you find any other edge cases.
