### ISSUE TITLE
Is there a function similar to sp-next-sexp?

### ISSUE THREAD

**Issue by Somelauw** [abo-abo/lispy#369]
In smartparens this goes to the beginning of the next symbol or sexp.
It's different from lispy-down because lispy-down goes to the next sexp starting with "(", but ignores symbols.
It's also different from lispy-forward-sexp, because it goes to the beginning.

The simplest implementation is something like
(forward-sexp 2)
(backward-sexp)
But a good implementation needs more thought.

Does such a function perhaps already exist under a different name?

**Comment by Somelauw** [comment]
Maybe this function may not really fit in lispy, because there isn't a lispy-forward-sexp either. I can combine lispy with smartparens for this function.

**Comment by abo-abo** [comment]
> but ignores symbols.

You can use region to navigate symbols.

Example:

```elisp
|((foo)
  bar
  (baz))
```

It's easy to navigate to `(foo)` - <kbd>f</kbd>. And to `(baz)` - <kbd>ff</kbd>.

But if you use the region, you can also navigate to `bar`: <kbd>fmj</kbd>. Well, <kbd>2m</kbd> is shorter, but the point is that if the region is active, <kbd>j</kbd>/<kbd>k</kbd>/<kbd>w</kbd>/<kbd>s</kbd> etc work on symbols.

There's no `lispy-forward-sexp` because there already is a built-in `forward-sexp`. Emacs already has many nice functions for editing Lisp by default.

**Comment by Somelauw** [comment]
> You can use region to navigate symbols.
Makes sense.
