### ISSUE TITLE
Add toggle for region manipulation commands

### ISSUE THREAD

**Issue by dangirsh** [abo-abo/lispy#402]
The Lisp structure editing commands are very useful on their own without the addition of the region manipulation counterparts. I see these as extra features that can be jarring to some workflows. For example, I'm very accustomed to inserting over a region to replace it. 

Looking at the code, it seems like we could just replace `region-active-p` calls to a wrapper which checks some toggle var.

**Comment by abo-abo** [comment]
> I'm very accustomed to inserting over a region to replace it.

You're removing quite a lot of flexibility then. Instead of having `a-z` and `A-Z` as commands at your disposal, potentially doing 52 different things, you have them do one (rather mundane) thing.  Within the recommended workflow:

- you can delete a region with <kbd>C-d</kbd>
- you can paste over a region with <kbd>P</kbd>

It's not a big change to add a flag to `lispy--insert-or-call` and do what you want. But I think you'd end up with a less efficient editing experience. If you still want it, please PR.

**Comment by dangirsh** [comment]
I agree that the default is more efficient. If I was only editing Lisp with Lispy all day, I'd happily readjust my habits. The "insert over selection" behavior is pervasive and primitive at this point - I doubt I'm the only one who finds it jarring.

**Comment by dangirsh** [comment]
(and I wish I WAS editing Lisp with Lispy all day, it's a fantastic tool :))
