### ISSUE TITLE
Helm not found

### ISSUE THREAD

**Issue by mbork** [abo-abo/lispy#44]
Hi, Oleh,

I tried to install lispy from melpa, and got an error about helm not found. I don't use Helm (and don't want to - I'm an Icicles guy). Any suggestions?

**Comment by abo-abo** [comment]
This is strange, since you can see [here](http://melpa.org/#/lispy) that it depends on `helm`.
So `helm` should have been installed automatically.

`helm` is used for completion in <kbd>g</kbd> and <kbd>G</kbd> to navigate between the tags.
I'm not familiar with Icicles, maybe you can do it through that.

There's also navigation within current top-level sexp through <kbd>y</kbd>, but it's not essential.

If Icicles offers a generic API for completion and can handle 30000 candidates at once, I could
make it an option for <kbd>g</kbd> and <kbd>G</kbd>.

It's possible to not require `helm` at top-level, if you're so averse to it. I could make that change.

**Comment by mbork** [comment]
Hi there,

and thanks for a quick response!

On 2015-01-29, at 07:49, Oleh Krehel wrote:

> This is strange, since you can see [here](http://melpa.org/#/lispy) that it depends on `helm`.
> So `helm` should have been installed automatically.

Well, my fault: I did mess a bit with repositories (melpa vs melpa
stable, for instance), and probably broke something.  I guess I'll have
to reboot my Emacs someday;-).

> `helm` is used for completion in <kbd>g</kbd> and <kbd>G</kbd> to navigate between the tags.
> I'm not familiar with Icicles, maybe you can do it through that.

Most probably yes.  (It's rather difficult to find anything
completion-related that Icicles cannot do...)

> There's also navigation within current top-level sexp through <kbd>y</kbd>, but it's not essential.
>
> If Icicles offers a generic API for completion and can handle 30000 candidates at once, I could
> make it an option for <kbd>g</kbd> and <kbd>G</kbd>.

It does offer an API for completion in a way (you just use vanilla
Emacs' completion commands, which it intercepts), but might have
performance troubles with huge lists.  Out of curiosity: why would there
exist 30k candidates lists in the first place?

> It's possible to not require `helm` at top-level, if you're so averse to it. I could make that change.

It might not be a problem.  I don't want to ask you to do unnecessary
work.  Much depends on whether Helm and Icicles can coexist.  (I'm a bit
afraid to check it on my Emacs installation, but I guess I'll just try
and see.)

Best,

**Comment by abo-abo** [comment]
> It does offer an API for completion in a way (you just use vanilla
> Emacs' completion commands, which it intercepts)

OK, I'll have to check it out some time.

> why would there exist 30k candidates

There are 24327 top-level tags currently in `git/emacs/lisp` source,
96393 if all sub-directories are included.

> Much depends on whether Helm and Icicles can coexist

Like any good package, `(require 'helm)` does not change Emacs
behavior.  You'd have to explicitly call `helm-mode` to change things
(similar to `ido-mode`).
