### ISSUE TITLE
How do I configure Lispy so that it doesn't use special enhancements for Clojure?

### ISSUE THREAD

**Issue by NightMachinary** [abo-abo/lispy#447]
I use Lispy only for structural editing, and I don't need fancy IDE features. How can I disable them? They always break my CIDER.

**Comment by vitorqb** [comment]
@NightMachinary I also wanted a similar feature (just the structural editing), so I [forked](https://github.com/vitorqb/lightlispy) lispy and kept only the part of the code I use (which are the basic functionalities and nothing else). No evaluations. 

There are **many bugs** and I **don't promise any maintenance**, but I have been using it happily for some months already in clojure(script) and elisp, so maybe it helps you.

**Comment by NightMachinary** [comment]
Thanks:-)

**Comment by abo-abo** [comment]
The only time lispy interfaces with CIDER is when you use the eval features, e.g. <kbd>e</kbd> or <kbd>xf</kbd>. If you don't use them, all that's left is the structural editing.

If the eval features break CIDER, please make a bug report.

**Comment by vitorqb** [comment]
@abo-abo correct me if I'm wrong, but don't lispy inject dependencies for cider?

Like here: 
https://github.com/abo-abo/lispy/blob/master/le-clojure.el#L112

I also suspect that something else trigger the evaluation of `lispy-clojure.clj` because this file would be load almost automatically after I started a repl. But I'm not 100% sure on that.

**Comment by abo-abo** [comment]
OK, `lispy-mode` no longer calls `(require 'le-clojure)`.

le-clojure is valuable in my opinion, if it doesn't work for you, please report a bug.
