### ISSUE TITLE
Please DO NOT require hydra

### ISSUE THREAD

**Issue by c02y** [abo-abo/lispy#46]
When I update my packages from melpa,  I noticed that the hydra package][https://github.com/abo-abo/hydra] of yours has been downloaded and you require it inside lispy package, but only a few lines of code is related, I don't know if you are going to add more or not, but I rarely use hydra, and honestly, the functions lispy provides is too much, I already disable several lispy-mode-map bindings, 

lispy is great, it provides a lot of commands I won't even imagine, the bad thing is, it will use a lot of bindings to replace the default ones related to `Ctrl` and `Alt` which I already defined and maybe will use in my own `init.el`.

Have you ever thought about making it cleaner and cutting off some features/functions that are not that important, you really don't have to take every possibility into consideration and put it into lispy.

**Comment by bcarrell** [comment]
Going to take a bit of a different stance:  I personally like the experimental features and aggressive changes and fast development pace.  If I don't like a particular feature, I'll modify them.  I'd like to keep Hydra and see what it can bring.

**Comment by abo-abo** [comment]
I have the same opinion: `lispy` is very far from stable. I keep trying new ideas; some of
them work, some of them don't work. But to get the really good ones I have to try a lot of
new ideas.

Besides, `(require 'hydra)` does absolutely nothing to modify the behavior of your Emacs.
It just defines a couple of macros and nothing is done unless the user calls these macros
in her config. What I did so far, was to make the previously unbound <kbd>z</kbd> into a
Hydra.  No other behaviors were changed. But you should expect that <kbd>x</kbd> will
become a Hydra eventually, possibly with current behavior as a fallback through a custom
var.

Note that this is *completely different* from the currently very popular `evil` package which
installs **and enables** `undo-tree` even when `evil-mode` is not on.

If you like to be conservative, you can stick to [stable](https://github.com/abo-abo/lispy/releases) versions of lispy.
Each time I release a new version, I list the user-visible changes, so that you can modify
them if you want in your own config.

Btw, here's my personal config; I don't just merge it into lispy willy-nilly:

```cl
(use-package lispy
    :load-path "~/git/lispy"
    :init
    (progn
      (define-key lispy-mode-map (kbd "φ") 'lispy-parens)
      (define-key lispy-mode-map (kbd "σ") 'lispy-braces)
      (define-key lispy-mode-map (kbd "ρ") 'lispy-brackets)
      (define-key lispy-mode-map (kbd "θ") 'lispy-quotes)
      (define-key lispy-mode-map (kbd "C-φ") 'lispy-parens-down)
      (define-key lispy-mode-map (kbd "χ") 'lispy-right)
      (define-key lispy-mode-map (kbd "C-M-a") 'lispy-beginning-of-defun)
      (define-key lispy-mode-map (kbd "C-x C-j") 'lispy-debug-step-in)
      (define-key lispy-mode-map (kbd "C-8") nil)
      (define-key lispy-mode-map (kbd "C-9") nil)
      (define-key lispy-mode-map (kbd "<return>") 'lispy-alt-line)
      (define-key lispy-mode-map (kbd "RET") 'lispy-newline-and-indent-plain)
      (define-key lispy-mode-map (kbd "C-M-h") 'lispy-backward)
      (setq lispy-helm-columns '(1 46 51 80))
      (setq lispy-no-permanent-semantic t)
      (set-face-background 'lispy-command-name-face "#d8d8f7")))
```

**Comment by c02y** [comment]
Please push [stable version of lispy][https://github.com/abo-abo/lispy/releases] to http://stable.melpa.org/packages/ so I can install it using package.el.

**Comment by abo-abo** [comment]
It's already there at http://stable.melpa.org/#/lispy.

**Comment by c02y** [comment]
Sorry, I didn't see it in the `*Packages*` buffer after installing it but I can get it at http://stable.melpa.org/packages/ , it turns out, if you've already installed it, there will not be another one from other repo, I have to remove the installed one and refresh the buffer.
