### ISSUE TITLE
Can’t type `#hash` before parentheses 

### ISSUE THREAD

**Issue by NightMachinary** [abo-abo/lispy#465]
Racket uses “#hash(...)” for hashmaps, and I can’t type it using Lispy.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by NightMachinary** [comment]
@abo-abo Thanks! Two things:
`c-u (` doesn't work properly and produces `( #hash)()` from `#hash()`.
if we have `(some stuff)`, we can't type `#hash` before it (to make it into `#hash(...)`.

I think treating `|#...(...)` as the start of the expression (instead of `#...|(...)`) will solve both of the above.

**Comment by abo-abo** [comment]
> c-u ( doesn't work properly and produces ( #hash)() from #hash().

<kbd>C-u (</kbd> inserts a pair and does a slurp, which in turn uses `forward-sexp`:

```racket
()|#hash((1 . 2) (3 . 4))
```

You can test that a `forward-sexp` from this position moves the point here:

```racket
()#hash|((1 . 2) (3 . 4))
```

instead of here:

```racket
()#hash((1 . 2) (3 . 4))|
```

So this bug should be solved in `scheme-mode` (e.g. by modifying syntax or defining `forward-sexp-function`) and not here.

> if we have (some stuff), we can't type #hash before it (to make it into #hash(...).

A patch to `lispy-hash` is welcome, e.g. "##" could insert "#hash" or something.
