### ISSUE TITLE
Lispy way of inserting at beginning / end of parens?

### ISSUE THREAD

**Issue by dvcrn** [abo-abo/lispy#491]
Sorry for the noob question but I have some issues figuring lispy out completely. I'm using it together with lispyville

If my cursor is in special at the beginning of a sexp like this
```
|(ns some.namespace)
```

What is the lispy way of inserting text at the beginning or end? Like

```
(ns some.namespace
    [|])
```

Similar to if I want to insert in between `ns` and `some.namespace`. 

I could:
- Use `d` to jump to the beginning / end of the sexp and use the arrow keys but that doesn't feel right. Also I'm using it with vim and usually don't touch the arrows

With marks:
- Use `d` to jump to the beginning / end of the sexp, hit `M-m` to mark the first/last element of the sexp, then navigate with `j`/`k` 
- Use `a` to jump to the symbol in question directly
- Use `3m` or something like that to mark the correct symbol

... but then how to insert before/after the mark without hitting DEL and retyping it?

**Comment by abo-abo** [comment]
> What is the lispy way of inserting text at the beginning or end? Like

One of the ways is: <kbd>3 SPC RET }</kbd>. Another is <kbd>2m RET }</kbd>. Another is <kbd>0m RET }</kbd>.

Personally, I would do: <kbd>C-f ;-v ;-r</kbd>. <kbd>;-v</kbd> is my binding for `lispy-alt-line` and <kbd>;-r</kbd> is my binding for `lispy-brackets`.

When I insert the whole thing: <kbd>;-f ns some.namespace ;-v ;-r</kbd>. Here, since I'm inserting, there's no need for the extra <kbd>C-f</kbd>.

> Similar to if I want to insert in between ns and some.namespace.

Select the symbol you want to insert after and press <kbd>SPC</kbd>. It will deactivate the region and insert a space.  You can select the symbol `ns` with either <kbd>mi</kbd> or <kbd>aa</kbd>.

**Comment by abo-abo** [comment]
Hi. If this answers your question, please close the issue.

**Comment by dvcrn** [comment]
Thanks for the response! Closing this
