### ISSUE TITLE
`lispy-delete-backward` broken with curly braces

### ISSUE THREAD

**Issue by bcarrell** [abo-abo/lispy#50]
Came across this one after I accidentally inserted curly braces...

`(foo bar baz {|})` -> <kbd>DEL</kbd> -> ` `

`(foo bar baz {}|)` -> <kbd>DEL</kbd> -> `)`

**Comment by abo-abo** [comment]
I think I saw an issue like this before.
This happens because curly braces are not part of Elisp syntax.
The function will work fine in Clojure or Scheme, but will fail for Elisp or CL.
Lispy relies on functions like `forward-list` that need the syntax set in order to work.
This can be fixed with:

```cl
(modify-syntax-entry ?\{ "(}")
(modify-syntax-entry ?\} "){")
```

Again, I'm not sure if `lispy` should modify the major-mode's syntax.
But I guess I can just do it and see if anyone complains:)

**Comment by bcarrell** [comment]
I agree that it probably shouldn't modify the syntax but it's somewhat aggravating when I make a mistake and want to get rid of it and it removes a ton of stuff.  When encountering symbol(s) that aren't part of the current syntax table, is it possible to call the bare functions?  e.g. `delete-backward-char`?

**Comment by abo-abo** [comment]
> e.g. delete-backward-char?

That would cause paren imbalance. Although without syntax they don't really count as parens.

**Comment by bcarrell** [comment]
Maybe `lispy-braces` should be a noop in Elisp unless I'm in a string or comment?  I won't need to delete them if I can't insert them!

**Comment by abo-abo** [comment]
That would probably be annoying. And it would be hard to write this:

```cl
(setq {asdf} 42)
```

**Comment by bcarrell** [comment]
shoot.
