### ISSUE TITLE
i have no idea to end the paren.

### ISSUE THREAD

**Issue by loyalpartner** [abo-abo/lispy#506]
```
(defun foo()
   body|<--cursor
```
i want to input ), but nothing happan.

**Comment by abo-abo** [comment]
If you're in this situation with lispy, it means something bad happened, since your parens are unbalanced.  Lispy commands will not un-balance the parens, assuming you start out with a balanced buffer. A common source of unbalanced parens is a bad copy-paste.

Anyway, you can insert `)` with <kbd>C-q )</kbd>.

**Comment by loyalpartner** [comment]
tks! i
