### ISSUE TITLE
[ and ] in clojure-mode

### ISSUE THREAD

**Issue by julienfantin** [abo-abo/lispy#83]
`(defn foo_)` with the cursor at `_`, when I type `[` - intending to insert an arglist - the cursor moves past the opening paren with `lispy-backward`, as opposed to simply inserting `[_]` (with paredit enabled).

I remapped those keys to nil in `lispy-mode-map-lispy`, but considering you wrote some clojure-specific support and those movements seem handy, I'm curious whether you have a different usage pattern for this specific use-case?

Cheers,
Julien

**Comment by abo-abo** [comment]
> (defn foo_) with the cursor at _, when I type
> [ - intending to insert an arglist - the cursor moves past the opening paren with lispy-backward, as opposed to simply inserting [_]

In my experience, navigation is very important. That's why <kbd>[</kbd> and <kbd>]</kbd> navigate and not insert by default.  To insert `[]`, you can use <kbd>}</kbd>.

> (with paredit enabled).

Show me your call to `lispy-set-key-theme`. The `lispy` and `paredit` parts should be exclusive, since they complete for the same key bindings.

> I remapped those keys to nil in lispy-mode-map-lispy, but
> considering you wrote some clojure-specific support and those
> movements seem handy, I'm curious whether you have a different usage
> pattern for this specific use-case?

To insert brackets, I'm using <kbd>ρ</kbd> from `lispy-mode-map-oleh`. But in this use-case I have something [better](https://github.com/abo-abo/oremacs/blob/github/snippets/clojure-mode/defn):


    # -*- mode: snippet -*-
    # name: defn
    # key: d
    # --
    (defn $1 [$2]
    $0)

For me `d` <kbd>C-o</kbd> (`aya-open-line`, which also expands yasnippets), inserts a function definition snippet in a bunch of languages (Elisp/Clojure/Octave/Scheme).

**Comment by julienfantin** [comment]
Ha! `}` works indeed. 

I now see that it is documented, so thanks for the reminder. You might want to emphasize this in the docs since it is very likely to confuse people trying out lispy with clojure, as it did me.

By paredit enabled, I meant the actual mode. I've found lispy and paredit to work well together, and though I'm not sure who's doing what anymore, it all works fine.

Also thanks for the aya mention, I'll make sure to give it a try!

**Comment by sp3ctum** [comment]
Thanks for pointing it out. It confused me too, but actually I like `}`! :+1:
