### ISSUE TITLE
just-a-question: how are you measure code coverage?

### ISSUE THREAD

**Issue by capitaomorte** [abo-abo/lispy#92]
This is just a question, not really an issue. I'm very curious as to how you're measuring code coverage as reported by https://coveralls.io/github/abo-abo/lispy. 

I know how to automate travis tests for emacs lisp programs but nothing for measure code coverage. There is a "testcover.el" package in Emacs, but it's quite broken I think.

Thanks!
João

**Comment by abo-abo** [comment]
I'm using undercover.el which depends on testcover.el. I've played with testcover.el and it does work, but the interface isn't great: it's based on faces rather than textual information.

The test coverage is measured by % of execution branches followed:

1. testcover.el "instruments" all if/cond/when ... branches using edebug.
2. ERT tests are run, and testcover counts how many times each branch was run; if it's not 0 then it's "covered"
3. The final percentage is # of "covered" branches / # of all branches.

It's not very easy to see what undercover.el actually does. But if you set `(setq undercover-force-coverage t)`, and:

    export TRAVIS=1
    export COVERALLS_REPO_TOKEN=1

before doing:

    make test

You will get to see the file generated by undercover in `/tmp/undercover_coveralls_report`.  For lispy, this file is 280K. It contains a huge vector with numbers and null values: those correspond to the branches that I mentioned.  Null I think means that the branch isn't supposed to be checked. And 0 means that the branch wasn't run at least once, which is the bad case.  A non-zero number shows how many times a particular branch was run; even if it's 1, it counts as "covered".

In my case the numbers are: 1671 cases of zeros, out of 4165 total, or 40%. This translates to 60% coverage.

The only tricky part about using undercover.el, which I had to figure out when I was setting up, is that you need to call `undercover` *before* you load any of your code, otherwise it won't work.

Also note that step 2 can actually be interactive: testcover doesn't care if it's ERT calling your functions or you: it just counts the numbers for each branch.

**Comment by capitaomorte** [comment]
@abo-abo, thanks very much for the detailed explanation. I grepped your repo and couldn't find a reference to any coverage tool, so it baffled me. Now I see the way you're using undercover.el

> I'm using undercover.el which depends on testcover.el.

It doesn't seem to depend on testcover.el anymore. Which might be a good thing...

> The only tricky part about using undercover.el, which I had to figure out when I was setting up, is that > you need to call undercover before you load any of your code, otherwise it won't work.

Seems to be related to the way it uses `file-name-handler-alist` to schedule a file being edebugged.

The macro issue is a problem with lisp macros in general. Unless elisp comes up with a code walker, we'll have to use debug specs on our macros, which isn't too bad anyway. What's the default behaviour when un-edebuggable macro is found? Are the lines counted as covered or uncovered? Oh right, it isn't line-based.

I also wonder if there can be any correlation between branches and line numbers at all. Or if it even makes sense. Perhaps it should count sexp's evaluated instead of branches. Or keep the branch count and perhaps assume pessimistically that every sexp down an un-edebuggable macro is a branching sexp. Perhaps I should ask the undercover.el author :-)

THanks!
João
